// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeCaseFiles.Api.Infrastructure.Sqlite;

#nullable disable

namespace OfficeCaseFiles.Api.Migrations.Sqlite
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260925133247_ConclusionReview")]
    partial class ConclusionReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.AnswerReceiptRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoiceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FirstTryCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionAfter")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "SubmissionId");

                    b.ToTable("AnswerReceipts", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.ConclusionReceiptRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceId1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceId2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "SubmissionId");

                    b.ToTable("ConclusionReceipts", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.ConclusionRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceId1")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceId2")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("InvestigationScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspectId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.ToTable("Conclusions", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.EncounterReceiptRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssistanceUsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClearedAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailuresAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionAfter")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "SubmissionId");

                    b.ToTable("EncounterReceipts", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.EvidenceRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Bookmarked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "EvidenceId");

                    b.ToTable("EvidenceProgress", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.InteractionReceiptRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionAfter")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "SubmissionId");

                    b.ToTable("InteractionReceipts", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.QuestionProgressRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstChoiceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PassedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "QuestionId");

                    b.ToTable("QuestionProgress", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.ReviewProgressRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewItemId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "ReviewItemId");

                    b.ToTable("ReviewProgress", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.ReviewReceiptRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionAfter")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "SubmissionId");

                    b.ToTable("ReviewReceipts", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssistanceUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EncounterCleared")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EncounterFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PlaySessions", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.AnswerReceiptRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.ConclusionReceiptRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.ConclusionRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithOne()
                        .HasForeignKey("OfficeCaseFiles.Api.Infrastructure.Sqlite.ConclusionRow", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.EncounterReceiptRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.EvidenceRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.InteractionReceiptRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.QuestionProgressRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.ReviewProgressRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.ReviewReceiptRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
