// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeCaseFiles.Api.Infrastructure.Sqlite;

#nullable disable

namespace OfficeCaseFiles.Api.Migrations.Sqlite
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260925043820_EvidenceProgress")]
    partial class EvidenceProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.EvidenceRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Bookmarked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "EvidenceId");

                    b.ToTable("EvidenceProgress", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.InteractionReceiptRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionAfter")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "SubmissionId");

                    b.ToTable("InteractionReceipts", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PlaySessions", (string)null);
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.EvidenceRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeCaseFiles.Api.Infrastructure.Sqlite.InteractionReceiptRow", b =>
                {
                    b.HasOne("OfficeCaseFiles.Api.Infrastructure.Sqlite.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
