// T27 V3 character sprite sheets, generated by scripts/art/characters-svg.py into
// public/assets/characters. Layout: rows down/up/side (side faces right), columns
// idle 0-3, walk 4-9, run 10-15; frame 80x120 with the foot at (40, 112).

export const CHARACTER_IDS = ['player', 'maya', 'leo', 'nora'] as const
export type CharacterId = typeof CHARACTER_IDS[number]

export const FRAME = { width: 80, height: 120, footY: 112 } as const
export const SHEET = { width: 1280, height: 360 } as const

export type SheetRow = 'down' | 'up' | 'side'
export type AnimState = 'idle' | 'walk' | 'run'
export type Facing4 = 'down' | 'up' | 'left' | 'right'

const ROWS: readonly SheetRow[] = ['down', 'up', 'side']
export const ANIM_STATES: readonly { state: AnimState; start: number; count: number; fps: number }[] = [
  { state: 'idle', start: 0, count: 4, fps: 4 },
  { state: 'walk', start: 4, count: 6, fps: 10 },
  { state: 'run', start: 10, count: 6, fps: 14 },
]

export const sheetKey = (id: CharacterId) => `char-${id}`
export const animKey = (id: CharacterId, row: SheetRow, state: AnimState) => `${id}-${row}-${state}`
export const sheetUrl = (id: CharacterId, base = '/') =>
  `${base.endsWith('/') ? base : `${base}/`}assets/characters/${id}-sheet.svg`
export const portraitUrl = (id: CharacterId, base = '/') =>
  `${base.endsWith('/') ? base : `${base}/`}assets/characters/${id}-portrait.svg`

export type SheetFrame = { name: string; x: number; y: number }

export function sheetFrames(): SheetFrame[] {
  return ROWS.flatMap((row, r) => ANIM_STATES.flatMap(({ state, start, count }) =>
    Array.from({ length: count }, (_, i) => ({
      name: `${row}-${state}-${i}`, x: (start + i) * FRAME.width, y: r * FRAME.height,
    }))))
}

export function isCharacterId(value: string): value is CharacterId {
  return (CHARACTER_IDS as readonly string[]).includes(value)
}

export type CharacterAnim = { facing: Facing4; row: SheetRow; flipX: boolean; state: AnimState }

/** Presentation-only animation choice; never feeds back into movement or collision. */
export function characterAnim(input: { x: number; y: number }, running: boolean, dodging: boolean,
  previous: Facing4): CharacterAnim {
  const moving = input.x !== 0 || input.y !== 0
  const facing: Facing4 = input.x < 0 ? 'left' : input.x > 0 ? 'right'
    : input.y < 0 ? 'up' : input.y > 0 ? 'down' : previous
  const row: SheetRow = facing === 'left' || facing === 'right' ? 'side' : facing
  const state: AnimState = dodging || (moving && running) ? 'run' : moving ? 'walk' : 'idle'
  return { facing, row, flipX: facing === 'left', state }
}

/** Maps an NPC interaction id (npc-maya) to its portrait character, if any. */
export function portraitFor(interactionId: string | null | undefined): CharacterId | null {
  const id = interactionId?.replace(/^npc-/, '') ?? ''
  return interactionId?.startsWith('npc-') && isCharacterId(id) ? id : null
}
