// T27 V2 direction-A office textures. Files are generated by scripts/art/office-svg.py
// into public/assets/office and listed in docs/assets/manifest.md.

export type ArtKey =
  | 'floor-lobby' | 'floor-office' | 'floor-archive' | 'floor-meeting'
  | 'desk' | 'cabinet' | 'planter' | 'meeting-table'
  | 'lamp' | 'plant-small' | 'papers' | 'water-cooler' | 'rug-lobby' | 'restricted-tape'
  | 'checkpoint-pad' | 'scanner-drone' | 'evidence-card'

export type ArtAsset = { key: ArtKey; width: number; height: number; footY?: number }

// footY is the pixel row that sits on the collision footprint's front edge.
export const OFFICE_ART: readonly ArtAsset[] = [
  { key: 'floor-lobby', width: 128, height: 128 },
  { key: 'floor-office', width: 128, height: 128 },
  { key: 'floor-archive', width: 128, height: 128 },
  { key: 'floor-meeting', width: 128, height: 128 },
  { key: 'desk', width: 280, height: 176, footY: 160 },
  { key: 'cabinet', width: 150, height: 320, footY: 304 },
  { key: 'planter', width: 170, height: 200, footY: 186 },
  { key: 'meeting-table', width: 265, height: 200, footY: 186 },
  { key: 'lamp', width: 60, height: 150, footY: 140 },
  { key: 'plant-small', width: 64, height: 100, footY: 92 },
  { key: 'papers', width: 90, height: 50 },
  { key: 'water-cooler', width: 60, height: 140, footY: 132 },
  { key: 'rug-lobby', width: 240, height: 150 },
  { key: 'restricted-tape', width: 128, height: 16 },
  { key: 'checkpoint-pad', width: 140, height: 80 },
  { key: 'scanner-drone', width: 80, height: 80 },
  { key: 'evidence-card', width: 56, height: 56 },
]

export function artUrl(key: ArtKey, base = '/'): string {
  return `${base.endsWith('/') ? base : `${base}/`}assets/office/${key}.svg`
}

export function artAsset(key: ArtKey): ArtAsset {
  const asset = OFFICE_ART.find(item => item.key === key)
  if (!asset) throw new Error(`Unknown office art key ${key}`)
  return asset
}

/** Phaser origin that places an image's foot row on the footprint front edge. */
export function footOrigin(key: ArtKey): { x: number; y: number } {
  const asset = artAsset(key)
  return { x: 0.5, y: (asset.footY ?? asset.height) / asset.height }
}

export type Zone = { id: 'lobby' | 'office' | 'archive' | 'meeting'; floor: ArtKey; fallback: number
  x: number; y: number; width: number; height: number }

// Covers FLOOR (64,142)-(1536,938) without gaps; archive/meeting split at the scanner corridor.
export const ZONES: readonly Zone[] = [
  { id: 'lobby', floor: 'floor-lobby', fallback: 0xe9cfa3, x: 64, y: 142, width: 356, height: 796 },
  { id: 'office', floor: 'floor-office', fallback: 0xbfe3d8, x: 420, y: 142, width: 580, height: 796 },
  { id: 'archive', floor: 'floor-archive', fallback: 0xefe3cc, x: 1000, y: 142, width: 536, height: 378 },
  { id: 'meeting', floor: 'floor-meeting', fallback: 0xcfe9dc, x: 1000, y: 520, width: 536, height: 418 },
]

export type Decor = { key: ArtKey; x: number; y: number; decal?: boolean }

// Non-colliding details, placed away from interaction radii and main routes.
export const DECOR: readonly Decor[] = [
  { key: 'rug-lobby', x: 240, y: 560, decal: true },
  { key: 'water-cooler', x: 110, y: 240 },
  { key: 'lamp', x: 110, y: 900 },
  { key: 'plant-small', x: 395, y: 200 },
  { key: 'plant-small', x: 975, y: 910 },
  { key: 'papers', x: 1230, y: 250, decal: true },
  { key: 'papers', x: 640, y: 250, decal: true },
  { key: 'lamp', x: 1505, y: 230 },
]

/** True only for a parseable SVG document; rejects HTML fallbacks served with status 200. */
export function isSvgDocument(text: string): boolean {
  if (!/^\s*(<\?xml[^>]*>\s*)?<svg[\s>]/i.test(text)) return false
  if (typeof DOMParser === 'undefined') return true
  const doc = new DOMParser().parseFromString(text, 'image/svg+xml')
  return doc.documentElement.nodeName === 'svg' && doc.getElementsByTagName('parsererror').length === 0
}
